apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: almoghindi/expiration
          env:
            - name: KAFKA_BROKER
              value: kafka-srv:9092
            - name: KAFKA_CLIENT_ID
              value: expiration
            - name: REDIS_HOST
              value: expiration-redis-srv
